"""adiciona sistema de tags para transacoes

Revision ID: ad252fbd3b6e
Revises: d70d5519cb9f
Create Date: 2025-12-27 19:05:21.778567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad252fbd3b6e'
down_revision: Union[str, Sequence[str], None] = 'd70d5519cb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_nome'), 'tag', ['nome'], unique=True)
    op.create_table('transacaotag',
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('transacao_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacaotag')
    op.drop_index(op.f('ix_tag_nome'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
