"""adiciona campo valor_original em transacao

Revision ID: d70d5519cb9f
Revises: 448cceacb835
Create Date: 2025-12-27 18:28:12.109383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70d5519cb9f'
down_revision: Union[str, Sequence[str], None] = '448cceacb835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('valor_original', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transacao', 'valor_original')
    # ### end Alembic commands ###
