"""adiciona sistema de regras automaticas

Revision ID: 70528d8e9c5f
Revises: ad252fbd3b6e
Create Date: 2025-12-28 12:48:57.214227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70528d8e9c5f'
down_revision: Union[str, Sequence[str], None] = 'ad252fbd3b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo_acao', sa.Enum('ALTERAR_CATEGORIA', 'ADICIONAR_TAGS', 'ALTERAR_VALOR', name='tipoacao'), nullable=False),
    sa.Column('criterio_tipo', sa.Enum('DESCRICAO_EXATA', 'DESCRICAO_CONTEM', 'CATEGORIA', name='criteriotipo'), nullable=False),
    sa.Column('criterio_valor', sa.String(), nullable=False),
    sa.Column('acao_valor', sa.String(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regra_nome'), 'regra', ['nome'], unique=False)
    op.create_index(op.f('ix_regra_prioridade'), 'regra', ['prioridade'], unique=False)
    op.create_table('regratag',
    sa.Column('regra_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['regra_id'], ['regra.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('regra_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regratag')
    op.drop_index(op.f('ix_regra_prioridade'), table_name='regra')
    op.drop_index(op.f('ix_regra_nome'), table_name='regra')
    op.drop_table('regra')
    # ### end Alembic commands ###
