"""adiciona campo data_fatura em transacao

Revision ID: 448cceacb835
Revises: cf2c36ca1c82
Create Date: 2025-12-27 11:20:37.120573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448cceacb835'
down_revision: Union[str, Sequence[str], None] = 'cf2c36ca1c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('data_fatura', sa.Date(), nullable=True))
    # Alteração manual: especificar USING para conversão de tipo
    op.execute("ALTER TABLE transacao ALTER COLUMN tipo TYPE tipotransacao USING tipo::tipotransacao")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alteração manual: reverter tipo para VARCHAR
    op.execute("ALTER TABLE transacao ALTER COLUMN tipo TYPE VARCHAR")
    op.drop_column('transacao', 'data_fatura')
    # ### end Alembic commands ###
