"""adiciona_validacoes_edge_cases

Revision ID: 60991599f87f
Revises: 89605a63827e
Create Date: 2026-01-04 12:38:19.912453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60991599f87f'
down_revision: Union[str, Sequence[str], None] = '89605a63827e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: adiciona unique constraints para regras e tags case-insensitive."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Alterar índice de regra.nome para unique
    op.drop_index(op.f('ix_regra_nome'), table_name='regra')
    op.create_index(op.f('ix_regra_nome'), 'regra', ['nome'], unique=True)
    
    # Alterar índice de regra.prioridade para unique
    op.drop_index(op.f('ix_regra_prioridade'), table_name='regra')
    op.create_index(op.f('ix_regra_prioridade'), 'regra', ['prioridade'], unique=True)
    
    # Criar índice case-insensitive para tag.nome
    op.drop_index(op.f('ix_tag_nome'), table_name='tag')
    op.create_index(op.f('ix_tag_nome'), 'tag', ['nome'], unique=False)
    
    # Criar índice unique usando expressão LOWER(nome) para case-insensitive
    op.execute('CREATE UNIQUE INDEX ix_tag_nome_lower ON tag (LOWER(nome))')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remover índice case-insensitive
    op.execute('DROP INDEX IF EXISTS ix_tag_nome_lower')
    
    # Restaurar índice original de tag.nome
    op.drop_index(op.f('ix_tag_nome'), table_name='tag')
    op.create_index(op.f('ix_tag_nome'), 'tag', ['nome'], unique=True)
    
    # Restaurar índice de regra.prioridade não-unique
    op.drop_index(op.f('ix_regra_prioridade'), table_name='regra')
    op.create_index(op.f('ix_regra_prioridade'), 'regra', ['prioridade'], unique=False)
    
    # Restaurar índice de regra.nome não-unique
    op.drop_index(op.f('ix_regra_nome'), table_name='regra')
    op.create_index(op.f('ix_regra_nome'), 'regra', ['nome'], unique=False)
    # ### end Alembic commands ###
