"""adiciona tabela configuracao

Revision ID: 856715defdd8
Revises: 3f28e19cbaf8
Create Date: 2026-01-05 22:31:38.495982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856715defdd8'
down_revision: Union[str, Sequence[str], None] = '3f28e19cbaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_tag_nome_lower_unique'), table_name='tag')
    op.drop_index(op.f('ix_tag_nome_lower'), table_name='tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tag_nome_lower'), 'tag', [sa.literal_column('lower(nome::text)')], unique=True)
    op.create_index(op.f('idx_tag_nome_lower_unique'), 'tag', [sa.literal_column('lower(nome::text)')], unique=True)
    # ### end Alembic commands ###
